"""
HTML reporter — generates interactive HTML evaluation reports.
"""

import json
from pathlib import Path
from typing import Optional

from ..models import EvalSuiteResult, Verdict

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>EvalKit Report — {suite_name}</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: #0f172a; color: #e2e8f0; padding: 2rem; }}
.container {{ max-width: 1000px; margin: 0 auto; }}
h1 {{ font-size: 1.8rem; margin-bottom: 0.5rem; }}
h2 {{ font-size: 1.3rem; margin: 1.5rem 0 0.8rem; color: #a78bfa; }}
.meta {{ color: #94a3b8; font-size: 0.9rem; margin-bottom: 1.5rem; }}
.cards {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; margin: 1.5rem 0; }}
.card {{ background: #1e293b; border-radius: 12px; padding: 1.2rem; text-align: center; }}
.card .value {{ font-size: 2rem; font-weight: bold; color: #7c3aed; }}
.card .label {{ color: #94a3b8; font-size: 0.85rem; margin-top: 0.3rem; }}
.card.pass .value {{ color: #22c55e; }}
.card.fail .value {{ color: #ef4444; }}
.card.warn .value {{ color: #f59e0b; }}
table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
th {{ background: #1e293b; padding: 0.8rem; text-align: left; font-size: 0.85rem; color: #94a3b8; }}
td {{ padding: 0.8rem; border-bottom: 1px solid #1e293b; font-size: 0.9rem; }}
tr:hover td {{ background: #1e293b44; }}
.bar {{ display: inline-block; height: 8px; border-radius: 4px; background: #334155; width: 100px; position: relative; }}
.bar-fill {{ height: 100%; border-radius: 4px; background: #7c3aed; }}
.pass-badge {{ color: #22c55e; font-weight: bold; }}
.fail-badge {{ color: #ef4444; font-weight: bold; }}
.error-badge {{ color: #f59e0b; font-weight: bold; }}
.metric-row {{ display: flex; align-items: center; gap: 0.8rem; margin: 0.5rem 0; }}
.metric-name {{ width: 180px; font-weight: 500; }}
.metric-score {{ width: 60px; text-align: right; }}
.details {{ margin: 1.5rem 0; }}
.case-card {{ background: #1e293b; border-radius: 8px; padding: 1rem; margin: 0.8rem 0; }}
.case-header {{ display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem; }}
.case-input {{ color: #94a3b8; font-size: 0.9rem; }}
.case-response {{ margin-top: 0.5rem; padding: 0.5rem; background: #0f172a; border-radius: 4px; font-size: 0.85rem; }}
footer {{ margin-top: 2rem; text-align: center; color: #64748b; font-size: 0.8rem; }}
</style>
</head>
<body>
<div class="container">
<h1>📊 EvalKit Report</h1>
<div class="meta">{suite_name} · Model: {model} · Run: {run_id}</div>

<div class="cards">
    <div class="card {pass_class}"><div class="value">{pass_rate}</div><div class="label">Pass Rate</div></div>
    <div class="card"><div class="value">{avg_score}</div><div class="label">Avg Score</div></div>
    <div class="card"><div class="value">{avg_latency}</div><div class="label">Avg Latency</div></div>
    <div class="card"><div class="value">{total_cost}</div><div class="label">Total Cost</div></div>
</div>

<h2>Metrics Summary</h2>
<div>{metrics_html}</div>

<h2>Case Results ({total} cases)</h2>
<div class="details">{cases_html}</div>

<footer>Generated by EvalKit v0.1.0 · Built by Edwin Isac</footer>
</div>
</body>
</html>"""


class HTMLReporter:
    """Generates HTML evaluation reports."""

    def generate(self, result: EvalSuiteResult) -> str:
        """Generate an HTML report string."""
        pass_rate = f"{result.pass_rate:.0%}"
        pass_class = "pass" if result.pass_rate >= 0.8 else "warn" if result.pass_rate >= 0.5 else "fail"

        metrics_html = self._metrics_section(result)
        cases_html = self._cases_section(result)

        return HTML_TEMPLATE.format(
            suite_name=result.suite_name,
            model=result.model,
            run_id=result.run_id,
            pass_rate=pass_rate,
            pass_class=pass_class,
            avg_score=f"{result.avg_score:.2f}",
            avg_latency=f"{result.avg_latency_ms:.0f}ms",
            total_cost=f"${result.total_cost_usd:.4f}",
            metrics_html=metrics_html,
            cases_html=cases_html,
            total=result.total_cases,
        )

    def save(self, result: EvalSuiteResult, path: Path) -> Path:
        """Save HTML report to file."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.generate(result))
        return path

    def _metrics_section(self, result: EvalSuiteResult) -> str:
        summary = result.metric_summary()
        if not summary:
            return "<p>No metrics.</p>"

        rows = []
        for name, stats in summary.items():
            pct = int(stats["avg"] * 100)
            color = "#22c55e" if stats["avg"] >= 0.7 else "#f59e0b" if stats["avg"] >= 0.5 else "#ef4444"
            rows.append(
                f'<div class="metric-row">'
                f'<span class="metric-name">{name}</span>'
                f'<div class="bar"><div class="bar-fill" style="width:{pct}%;background:{color}"></div></div>'
                f'<span class="metric-score">{stats["avg"]:.2f}</span>'
                f'</div>'
            )
        return "\n".join(rows)

    def _cases_section(self, result: EvalSuiteResult) -> str:
        cards = []
        for i, cr in enumerate(result.case_results):
            icon = "✅" if cr.passed else "❌"
            badge_cls = "pass-badge" if cr.passed else "fail-badge"

            metrics_list = " · ".join(
                f'<span class="{self._verdict_class(mr.verdict)}">{mr.metric_name}: {mr.score:.2f}</span>'
                for mr in cr.metric_results
            )

            input_preview = cr.case.input[:150]
            response_preview = cr.response.text[:300]

            cards.append(
                f'<div class="case-card">'
                f'<div class="case-header">'
                f'<span>{icon} Case {i+1}</span>'
                f'<span class="{badge_cls}">{cr.avg_score:.2f}</span>'
                f'</div>'
                f'<div class="case-input">{input_preview}</div>'
                f'<div class="case-response">{response_preview}</div>'
                f'<div style="margin-top:0.5rem;font-size:0.8rem;">{metrics_list}</div>'
                f'</div>'
            )
        return "\n".join(cards)

    @staticmethod
    def _verdict_class(verdict: Verdict) -> str:
        if verdict == Verdict.PASS:
            return "pass-badge"
        elif verdict == Verdict.FAIL:
            return "fail-badge"
        return "error-badge"
